version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 10
      runas: ec2-user